spring.application.name=Springsecuritydemo
server.port=8091
spring.security.user.password=welcome
spring.security.user.name=welcome
spring.h2.console.enabled=true
spring.h2.console.path=/h2
#spring.data.jpa.repositories.enabled=true
spring.jpa.hibernate.ddl-auto=update
#https://www.geeksforgeeks.org/spring-boot-3-0-jwt-authentication-with-spring-security-using-mysql-database/