spring.application.name=Springsecuritydemo
server.port=8090
#spring.security.user.password=welcome
#spring.security.user.name=welcome
#spring.datasource.url=jdbc:h2:mem:secu;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS SECUREDB

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.data.jpa.repositories.enabled=true
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
#spring.datasource.url=jdbc:h2:file:./testdb

#https://www.geeksforgeeks.org/spring-boot-3-0-jwt-authentication-with-spring-security-using-mysql-database/